export enum ActionType {
    VIEW_USER_LIST,

    CHANGE_LOGIN_HOST,
    CHANGE_LOGIN_PORT,
    CHANGE_LOGIN_USERNAME,
    CHANGE_LOGIN_PASSWORD,
    CHANGE_LOGIN_FORM, //XXX: experimental
    INVALID_LOGIN_SUBMIT,
    LOGIN_SUCCESS,
    LOGIN_FAIL,

    CLICK_ID_MENU,
    CLICK_CONFIG_MENU,

    USER_EDIT_ON,
    USER_EDIT_CANCEL,
    USER_ADD_CANCEL,
    OPEN_USER_ADD,
    USER_TOGGLE_VIEW,
    CHANGE_USER_USERNAME,
    CHANGE_USER_FIRSTNAME,
    CHANGE_USER_LASTNAME,
    CHANGE_USER_EMAIL,
    INVALID_USER_SUBMIT,

    VIEW_CLIENT_LIST,
    SAVE_CLIENT_NAME_EDIT,
    SAVE_CLIENT_URL_EDIT,
    SAVE_DEFAULT_TIMEZONE_EDIT,

    SAVE_NEW_CLIENT,

    PROFILE_CHANGE_PASSWORD_INPUT,
    PROFILE_CHANGE_NEW_PASSWORD_INPUT,
    PROFILE_CHANGE_CONFIRM_INPUT
}   