export enum ActionType {
    VIEW_USER_LIST,

    CHANGE_LOGIN_HOST,
    CHANGE_LOGIN_PORT,
    CHANGE_LOGIN_USERNAME,
    CHANGE_LOGIN_PASSWORD,
    CHANGE_LOGIN_FORM, //XXX: experimental
    INVALID_LOGIN_SUBMIT,

    VIEW_CLIENT_LIST,
    SAVE_CLIENT_NAME_EDIT,
    SAVE_CLIENT_URL_EDIT,
    SAVE_DEFAULT_TIMEZONE_EDIT,

    SAVE_NEW_CLIENT
}   